### ISSUE TITLE
pytest plugin might need to be adapted to changes in global config import

### ISSUE THREAD

**Issue by viv-vek** [agronholm/typeguard#455]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.21

### Python version

3.10

### What happened?

while running pytest test cases , it fails early with the following error.

**Import Error: cannot import name 'Config' from 'pytest'**
A bit of digging points to the the script _pytest_plugin.py in the following import

    **from pytest import Config, Parser**
pytest seems to have changed the how to import global config.

### How can we reproduce the bug?

run any pytest test case with latest version of pytest and typeguard 4.2.1.

**Comment by agronholm** [comment]
I just tested and this import works with pytest 8.1.1. What version are you running on?

**Comment by viv-vek** [comment]
i see ..we run with nox just checked the latest run its on pytest 6.2.5

**Comment by agronholm** [comment]
Typeguard's own tests require a minimum of pytest 7.

**Comment by viv-vek** [comment]
yes tested them now in two different environments. it works with pytest 8.1.1. Do you know of a minimum version of pytest that this support is in? Its because we have other libs which need to be compatible with the chosen version of pytest. so expecting to specify a range in my requirements file. Thanks a ton for a instant response.

**Comment by agronholm** [comment]
I believe it is specifically pytest 7, as they made backwards incompatible API changes there.
